/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VendingMachine } from './VendingMachine.js';
export * as factories from './factories/index.js';
export { VendingMachine__factory } from './factories/VendingMachine__factory.js';