/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface VendingMachineInterface extends Interface {
    getFunction(nameOrSignature: "addProduct" | "allProductIds" | "balanceOf" | "getProduct" | "nextProductId" | "owner" | "productCount" | "purchase" | "restock" | "updatePrice" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "PriceUpdated" | "ProductAdded" | "ProductPurchased" | "ProductRestocked" | "Withdrawal"): EventFragment;

    encodeFunctionData(functionFragment: 'addProduct', values: [string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'allProductIds', values?: undefined): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProduct', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextProductId', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'productCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'purchase', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'restock', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'updatePrice', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdraw', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'addProduct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allProductIds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProduct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextProductId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'productCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'purchase', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'restock', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace PriceUpdatedEvent {
      export type InputTuple = [id: BigNumberish, oldPrice: BigNumberish, newPrice: BigNumberish];
      export type OutputTuple = [id: bigint, oldPrice: bigint, newPrice: bigint];
      export interface OutputObject {id: bigint, oldPrice: bigint, newPrice: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProductAddedEvent {
      export type InputTuple = [id: BigNumberish, name: string, priceWei: BigNumberish, stock: BigNumberish];
      export type OutputTuple = [id: bigint, name: string, priceWei: bigint, stock: bigint];
      export interface OutputObject {id: bigint, name: string, priceWei: bigint, stock: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProductPurchasedEvent {
      export type InputTuple = [buyer: AddressLike, id: BigNumberish, qty: BigNumberish, totalPaid: BigNumberish];
      export type OutputTuple = [buyer: string, id: bigint, qty: bigint, totalPaid: bigint];
      export interface OutputObject {buyer: string, id: bigint, qty: bigint, totalPaid: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProductRestockedEvent {
      export type InputTuple = [id: BigNumberish, addedQty: BigNumberish, newStock: BigNumberish];
      export type OutputTuple = [id: bigint, addedQty: bigint, newStock: bigint];
      export interface OutputObject {id: bigint, addedQty: bigint, newStock: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawalEvent {
      export type InputTuple = [to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [to: string, amount: bigint];
      export interface OutputObject {to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface VendingMachine extends BaseContract {
    
    connect(runner?: ContractRunner | null): VendingMachine;
    waitForDeployment(): Promise<this>;

    interface: VendingMachineInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addProduct: TypedContractMethod<
      [name: string, priceWei: BigNumberish, initialStock: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    allProductIds: TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >
    

    
    balanceOf: TypedContractMethod<
      [user: AddressLike, id: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getProduct: TypedContractMethod<
      [id: BigNumberish, ],
      [[bigint, string, bigint, bigint] & {pid: bigint, name: string, priceWei: bigint, stock: bigint }],
      'view'
    >
    

    
    nextProductId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    productCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    purchase: TypedContractMethod<
      [id: BigNumberish, qty: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    restock: TypedContractMethod<
      [id: BigNumberish, addedQty: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updatePrice: TypedContractMethod<
      [id: BigNumberish, newPriceWei: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addProduct'): TypedContractMethod<
      [name: string, priceWei: BigNumberish, initialStock: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'allProductIds'): TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [user: AddressLike, id: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getProduct'): TypedContractMethod<
      [id: BigNumberish, ],
      [[bigint, string, bigint, bigint] & {pid: bigint, name: string, priceWei: bigint, stock: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'nextProductId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'productCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'purchase'): TypedContractMethod<
      [id: BigNumberish, qty: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'restock'): TypedContractMethod<
      [id: BigNumberish, addedQty: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePrice'): TypedContractMethod<
      [id: BigNumberish, newPriceWei: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'PriceUpdated'): TypedContractEvent<PriceUpdatedEvent.InputTuple, PriceUpdatedEvent.OutputTuple, PriceUpdatedEvent.OutputObject>;
getEvent(key: 'ProductAdded'): TypedContractEvent<ProductAddedEvent.InputTuple, ProductAddedEvent.OutputTuple, ProductAddedEvent.OutputObject>;
getEvent(key: 'ProductPurchased'): TypedContractEvent<ProductPurchasedEvent.InputTuple, ProductPurchasedEvent.OutputTuple, ProductPurchasedEvent.OutputObject>;
getEvent(key: 'ProductRestocked'): TypedContractEvent<ProductRestockedEvent.InputTuple, ProductRestockedEvent.OutputTuple, ProductRestockedEvent.OutputObject>;
getEvent(key: 'Withdrawal'): TypedContractEvent<WithdrawalEvent.InputTuple, WithdrawalEvent.OutputTuple, WithdrawalEvent.OutputObject>;

    filters: {
      
      'PriceUpdated(uint256,uint256,uint256)': TypedContractEvent<PriceUpdatedEvent.InputTuple, PriceUpdatedEvent.OutputTuple, PriceUpdatedEvent.OutputObject>;
      PriceUpdated: TypedContractEvent<PriceUpdatedEvent.InputTuple, PriceUpdatedEvent.OutputTuple, PriceUpdatedEvent.OutputObject>;
    

      'ProductAdded(uint256,string,uint256,uint256)': TypedContractEvent<ProductAddedEvent.InputTuple, ProductAddedEvent.OutputTuple, ProductAddedEvent.OutputObject>;
      ProductAdded: TypedContractEvent<ProductAddedEvent.InputTuple, ProductAddedEvent.OutputTuple, ProductAddedEvent.OutputObject>;
    

      'ProductPurchased(address,uint256,uint256,uint256)': TypedContractEvent<ProductPurchasedEvent.InputTuple, ProductPurchasedEvent.OutputTuple, ProductPurchasedEvent.OutputObject>;
      ProductPurchased: TypedContractEvent<ProductPurchasedEvent.InputTuple, ProductPurchasedEvent.OutputTuple, ProductPurchasedEvent.OutputObject>;
    

      'ProductRestocked(uint256,uint256,uint256)': TypedContractEvent<ProductRestockedEvent.InputTuple, ProductRestockedEvent.OutputTuple, ProductRestockedEvent.OutputObject>;
      ProductRestocked: TypedContractEvent<ProductRestockedEvent.InputTuple, ProductRestockedEvent.OutputTuple, ProductRestockedEvent.OutputObject>;
    

      'Withdrawal(address,uint256)': TypedContractEvent<WithdrawalEvent.InputTuple, WithdrawalEvent.OutputTuple, WithdrawalEvent.OutputObject>;
      Withdrawal: TypedContractEvent<WithdrawalEvent.InputTuple, WithdrawalEvent.OutputTuple, WithdrawalEvent.OutputObject>;
    
    };
  }